### ISSUE TITLE
Duplicated args if used with typing and autodoc_typehints = 'description'

### ISSUE THREAD

**Issue by lionel42** [sqlalchemyorg/sphinx-paramlinks#10]
When using  [typing](https://docs.python.org/3/library/typing.html) for the attributes, sphinx-paramlinks shows the args twice (once with the link and description and once with the type)

(Using autodoc for building the doc)

See how the arguments with the type hints are duplicated

![image](https://user-images.githubusercontent.com/43442120/122361563-a575d780-cf57-11eb-8558-ccd284ecc8a1.png)
![image](https://user-images.githubusercontent.com/43442120/122361598-b0c90300-cf57-11eb-8aca-c5209d752934.png)

```
def fail_typing(self, arg1, arg2: str, arg3: str):
        """Test

        :param arg1: description
        :type arg1: str
        :param arg2: description
        :param arg3: description
        :type arg3: str
        """
        pass```

**Comment by zzzeek** [comment]
hey there -

dogpile-cache uses sphinx paramlinks, in addition to being fully annotated, and im not seeing this issue: https://dogpilecache.sqlalchemy.org/en/latest/api.html#module-dogpile.cache.region

otherwise I'm not able to offer end-user support for sphinx-paramlinks, if you have a PR to fix the issue (a reproduction case would be helpful) we can put that in.

**Comment by lionel42** [comment]
Hi, 
Thanks for your help,
I think the error might come from a version issue of sphinx.
Do you know which versions were used to build dogpile ?

I was just trying to use sphinx paramlinks in the doc of my research project, so if I can't fix I won't deep too much.

**Comment by zzzeek** [comment]
probably an older version, so yes maybe something has changed.

**Comment by zzzeek** [comment]
that site is on 4.0.2.

**Comment by zzzeek** [comment]
4.0.2 is the latest

**Comment by lionel42** [comment]
Thanks for you help, I managed to find the trouble make: this line in conf.py

autodoc_typehints = 'description'

[doc: autodoc_typehints ](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints)

I just removed it and the bug was solved but then the types don't show next to the parameters.

Any plan to try to make it compatible with this mode of typehints ?
Otherwise I can close the issue

**Comment by zzzeek** [comment]
only if I seek to integrate autodoc_typehints with my own docs, which I might have to do at some point but it's not on the roadmap right now.

PRs are of course a quicker way to get to these things getting done.

**Comment by MaximilienLC** [comment]
Adding `"sphinx_autodoc_typehints"` to extensions & setting `paramlinks_hyperlink_param = "name"` fixes the duplication issue.
