### ISSUE TITLE
Compatibility with matlabdomain

### ISSUE THREAD

**Issue by peske** [sqlalchemyorg/sphinx-paramlinks#21]
Can this extension work with [`matlabdomain`](https://github.com/sphinx-contrib/matlabdomain)?

**Comment by zzzeek** [comment]
I have no idea!   the extension does what I need for my own project and that's about it!   check out https://github.com/sphinx-doc/sphinx/issues/11456 where there is interest in porting this extension to be part of Sphinx, that's where you'd want to let them know about other potential requirements.
