### ISSUE TITLE
Missimg last evrsion git tag

### ISSUE THREAD

**Issue by kloczek** [sqlalchemyorg/sphinx-paramlinks#8]
I have some automation which is checking pypi and if it is possible git repos and it processe git tag.
According to https://pypi.org/project/sphinx-paramlinks/ latest version is 0.5.0 however here there is no any git tags.
May I ask to add last version git tag ? (just version consisting digits and dots)

Regards

**Comment by zzzeek** [comment]
cc @CaselIT  if we can add automation here

**Comment by CaselIT** [comment]
sure, will add to the todo-list

**Comment by CaselIT** [comment]
In the meantime i've added a tag to 0.5.0: https://github.com/sqlalchemyorg/sphinx-paramlinks/releases/tag/0.5.0

**Comment by kloczek** [comment]
Thank you very much🙇‍♀️😀
